export { default as VSidebar } from '@/components/Sidebar.vue'
export { default as VNavbar } from '@/components/Navbar.vue'
export { default as VSidebarMenuMobil } from '@/components/aditionals/SidebarMenuMobil.vue'
export { default as VHistory } from '@/components/history/History.vue'
export { default as VTitlePage } from '@/components/aditionals/TitlePage.vue'
export { default as VTable } from '@/components/table/Table.vue'
export { default as VToolbarFilter } from '@/components/filters/ToolbarFilter.vue'
export { default as VButton } from '@/components/buttons/Button.vue'